version: '3'

services:
  web:
    build: ./docker/web/
    ports: 
       - 80:80
    volumes:
       - .:/var/www/html
    depends_on:
       - db
  db:
    image: postgres:9.3
    ports:
       - 5433:5432
    volumes:
     - ./docker/db:/docker-entrypoint-initdb.d
